# Generated by Django 4.0.6 on 2022-07-15 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_category', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(0, 'Muito Importante'), (1, 'Importante'), (2, 'Normal'), (3, 'Pouco Importante')], max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.categories')),
            ],
        ),
    ]
