# Generated by Django 4.0.6 on 2022-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Todo',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Muito Importante'), (1, 'Importante'), (2, 'Normal'), (3, 'Pouco Importante')]),
        ),
    ]
