# Generated by Django 4.0.6 on 2022-07-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_categories_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
